import { ChevronLeftIcon } from "@radix-ui/react-icons";
import Head from "next/head";
import { useRouter } from "next/router";

export default function Guide() {
  const router = useRouter();

  return (
    <>
      <Head>
        <title>Password generator - How to guide</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen">
        <div className="h-20" />
        <div className="text-white max-w-3xl mx-auto">
          <button
            onClick={() => router.push("/")}
            className="text-white flex items-center space-x-2 font-bold cursor-pointer"
          >
            <ChevronLeftIcon className="h-5 w-5" />
            <span>Back</span>
          </button>
          <div className="space-y-4">
            <div>
              <h1 className="text-7xl font-bold">Be unhackable</h1>
              <h2 className="text-3xl font-semibold">
                A guide to keeping your passwords secure.
              </h2>
            </div>
            <p>Rule 1: Don&apos;t share your passwords</p>
          </div>
        </div>
      </main>
    </>
  );
}
